apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../base
namespace: production
images:
- name: jmv2/hello-gitops
  newName: jmv2/hello-gitops
  newTag: 0.0.13

commonAnnotations:
  appVersion: 0.0.13

replicas:
- name: hello-gitops
  count: 3
