metadata:
  name: hello-gitops-staging
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    namespace: staging
    server: https://app-cluster-apiserver-1350953172.us-east-1.elb.amazonaws.com:6443
  project: default
  source:
    path: kustomize/staging
    repoURL: https://github.com/Platform9-Community/pf9-gitops-demo.git
    targetRevision: HEAD
  ignoreDifferences:
  - group: "apps"
    kind: "Deployment"
    jsonPointers:
    - /spec/replicas
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    retry:
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m0s
      limit: 2
    syncOptions:
    - CreateNamespace=true
    - RespectIgnoreDifferences=true
