apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- namespace.yaml
- ../base
namespace: dev
images:
- name: hello-gitops
  newName: jmv2/hello-gitops
  newTag: 0.0.23
- name: jmv2/hello-gitops
  newTag: 0.0.21
commonAnnotations:
  appVersion: 0.0.21
