apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- service.yaml
- ingress.yaml
namespace: default

commonLabels:
  app: hello-gitops

commonAnnotations:
  appVersion: 0.0.0
