apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- deployment.yaml
- hpa.yaml
- service.yaml
- service_monitor.yaml
namespace: default

images:
- name: jmv2/hello-gitops
  newName: jmv2/hello-gitops
  newTag: 0.0.0

commonLabels:
  app: hello-gitops

commonAnnotations:
  appVersion: 0.0.0
