apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: hello-gitops
  namespace: pf9-monitoring
spec:
  selector:
    matchLabels:
      app: hello-gitops
  endpoints:
  - port: http
  namespaceSelector:
    any: true
