name: Go

on:
  push:
    branches: [ main ]

jobs:
  detect_changes:
    runs-on: ubuntu-latest
    # Set job outputs to values from filter step
    outputs:
      build: ${{ steps.filter.outputs.build }}
    steps:
    - name: Check out repository code
      uses: actions/checkout@v2
      with:
        ref: main

    - uses: dorny/paths-filter@v2
      id: filter
      with:
        filters: |
          build:
            - 'cmd/**'

  bump_build_push:
    needs: detect_changes
    if: ${{ needs.detect_changes.outputs.build == 'true' }}
    name: Bump Version Build Docker Tag Repo
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        with:
          ref: main
      - name: Version Bump Action
        id: version-bump
        uses: 'phips28/gh-action-bump-version@master'
        with:
          skip-commit: 'true'
          skip-tag: 'true'
          skip-push: 'true'
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: 'Output Step'
        run: echo "new version tag ${{ steps.version-bump.outputs.newTag }}"
      - name: Setup Kustomize
        uses: imranismail/setup-kustomize@v1
        with:
          kustomize-version: "4.5.7"
      - name: Update Kubernetes Resources
        env:
          DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        run: |
          cd kustomize/dev
          kustomize edit set image hello-gitops=$DOCKER_USERNAME/hello-gitops:${{ steps.version-bump.outputs.newTag }}
          kustomize edit set annotation appVersion:${{ steps.version-bump.outputs.newTag }}
          cat kustomization.yaml
      - name: Build and push Docker image
        uses: docker/build-push-action@v1.1.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: ${{ secrets.DOCKER_USERNAME }}/hello-gitops
          tags: ${{ steps.version-bump.outputs.newTag }}, latest
      - name: Commit Files
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "CI: Bump to version ${{ steps.version-bump.outputs.newTag }}"
      - name: Tag repo
        uses: rickstaa/action-create-tag@v1
        with:
          tag: ${{ steps.version-bump.outputs.newTag }}
          message: "CI: bump to new version ${{ steps.version-bump.outputs.newTag }}"
      - name: Push Changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          tags: true
      - name: Set Argo Dev Version
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.4.11
          command: app patch hello-gitops-dev
          options: >
            --patch '{"metadata": { "labels": { "appVersion": "${{ steps.version-bump.outputs.newTag }}" }}}'
            --type merge
            --server cs-jmiller-ddu.platform9.net
            --grpc-web-root-path argocd
            --auth-token ${{ secrets.ARGOCD_TOKEN }}
      - name: Retrieve Staging version
        run: |
          echo "::set-output name=TAG_NAME::$(awk '/newTag/{print $2}' kustomize/staging/kustomization.yaml)"
        id: staging_tag
      - name: Set Argo Staging Version
        uses: clowdhaus/argo-cd-action/@main
        with:
          version: 2.4.11
          command: app patch hello-gitops-staging
          options: >
            --patch '{"metadata": { "labels": { "appVersion": "${{ steps.staging_tag.outputs.TAG_NAME }}" }}}'
            --type merge
            --server cs-jmiller-ddu.platform9.net
            --grpc-web-root-path argocd
            --auth-token ${{ secrets.ARGOCD_TOKEN }}
